controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

#Rutas
index:
    path: /users
    controller: App\Controller\UserController::index
